[package]
name = "pgp-split"
version = "0.1.0"
edition = "2021"
description = "pgp split"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/rpgp/cli"
readme = "README.md"
resolver = "2"

[dependencies]
